name: Jor3a-Ti9niya-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2019

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5  # Give some time for the download to complete

    - name: Install WinRAR
      run: |
        Invoke-WebRequest -Uri "https://www.rarlab.com/rar/winrar-x64-623.exe" -OutFile "$env:USERPROFILE\winrar.exe"
        Start-Process -FilePath "$env:USERPROFILE\winrar.exe" -ArgumentList "/S" -NoNewWindow -Wait

    - name: Verify WinRAR Installation
      run: |
        if (Test-Path "C:\Program Files\WinRAR\WinRAR.exe") { Write-Output "WinRAR installed successfully." } else { Write-Output "WinRAR installation failed." }

    - name: Create Download Directory
      run: New-Item -ItemType Directory -Path "D:\DownloadedFiles" -Force

    - name: Download Additional Files
      run: |
        $file1 = "D:\DownloadedFiles\file1.zip"
        $file2 = "D:\DownloadedFiles\file2.zip"
        $gdrive_base = "https://drive.google.com/uc?export=download&id="

        Invoke-WebRequest -Uri "$gdrive_base" + "1RZ1etCuigsKx3xpx15d32XkJA02YvRiw" -OutFile $file1 -UseBasicParsing
        Invoke-WebRequest -Uri "$gdrive_base" + "1viclVUYkeyFpx5cmGPkyaRbi5ExTP5gw" -OutFile $file2 -UseBasicParsing

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

    - name: www.toolboxlap.com
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

    - name: Keep the
